services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5216:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Database=Meh-Ecommerce;Username=postgres;Password=your_password_here
      - Authentication__Google__ClientId=your_client_id_here
      - Authentication__Google__ClientSecret=your_client_secret_here
      - Authentication__Google__RedirectUri=http://localhost:3000
      - AppSettings__Token=your_token_here
      - AppSettings__Issuer=MehJwt
      - AppSettings__Audience=MehAudience
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=Meh-Ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Meh-Ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
